# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.TextField()),
                ('hits', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('n', 'notice'), ('p', 'page')], default='n', max_length=2)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'content',
            },
        ),
    ]
