# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('name', models.CharField(blank=True, max_length=32, unique=True)),
                ('service_host', models.CharField(blank=True, max_length=32)),
                ('ui_host', models.CharField(blank=True, max_length=32)),
                ('redirect_uri', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'app',
            },
        ),
    ]
